FROM alpine:3.18@sha256:82d1e9d7ed48a7523bdebc18cf6290bdb97b82302a8a9c27d4fe885949ea94d1

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>"
LABEL org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.title="ownCloud CI Litmus"
LABEL org.opencontainers.image.url="https://hub.docker.com/r/owncloudci/litmus"
LABEL org.opencontainers.image.source="https://github.com/owncloud-ci/litmus"
LABEL org.opencontainers.image.documentation="https://github.com/owncloud-ci/litmus"

ARG LITMUS_VERSION

# renovate: datasource=github-tags depName=notroj/litmus versioning=loose
ENV LITMUS_VERSION="${LITMUS_VERSION:-0.14}"

ADD rootfs/ /
ADD src/ /tmp/src

RUN apk --update add --virtual .build-deps build-base openssl-dev libxml2-dev curl patch && \
  apk --update add bash openssl libxml2 && \
  mkdir -p /tmp/src/litmus && \
  curl -SsfL "https://notroj.github.io/litmus/litmus-${LITMUS_VERSION}.tar.gz" | tar xz --strip 1 -C /tmp/src/litmus && \
  cd /tmp/src/litmus && \
  cat /tmp/src/remove-locks.fail_complex_cond_put.patch | patch -p1 && \
  cat /tmp/src/remove-props.prophighunicode.patch | patch -p1 && \
  cat /tmp/src/revert-copymove.copy_shallow.patch | patch -p1 && \
  ./configure --with-ssl && \
  make && \
  PREFIX=/usr make install && \
  apk del .build-deps && \
  rm -rf /var/cache/apk/*

ENTRYPOINT ["/usr/local/bin/litmus-wrapper"]
WORKDIR /root
CMD []
